### ISSUE TITLE
Process/Pipe Viewer "pv" should add to the Repository

### ISSUE THREAD

**Issue by blackcrack** [AlmaLinux/updates#3]
Hi,  
  
i be at moment at a "blackysgate-Administrator" script, where confiurate  
all distros who be supportet, i have start at Fedora, now as 2nd Distro  
is almalinux at start (mind, rocky, debian, ubuntu, kubuntu fellows), 
there needs the pv, so the process viewer or named Pipe Viewer,
how ever, it lacks in Alma, it's by side of dialog, "dialog" is include.. :+1: 
could you are include pv  in the installcd ( i have use the "boot" rel 9.2  at moment in work) please ?
i have try it with dnf -y pb, has not works, 

edit: 
but as i add the epel-repo had found the pv .. and have installed then,
i would delete this issue by self, but there it's not possible, could you are delete the issue ?
thank you :)

best

**Comment by codyro** [comment]
I'm glad you figured it out! I'll mention the issue below in case anyone stumbles across this issue in the future.

`pv`, or `Pipe Viewer`, is available in the EPEL ("Extra Packages for Enterprise Linux") repository. You can install it by running the following command(s):

```shell
dnf -y install epel-release # Install EPEL repository
dnf -y install pv # Install pipe viewer
```

**Comment by blackcrack** [comment]
was 1999 at linux , i am old Mandrak'er (MDK) ;) i know Gaël Duval, he works at moment on /e/ ;)
but thy for the info :)

best and a happy day :)
